using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace APPBASE.Svcbiz
{
    public class valMENU
    {
        //Menu CPAR
        public const string CPAR_MASTER = "CPAR_MASTER";
        public const string CPAR_MASTER_DEPARTEMEN_INDEX = "CPAR_MASTER_DEPARTEMEN_INDEX";
        public const string CPAR_MASTER_DEPARTEMEN_DETAILS = "CPAR_MASTER_DEPARTEMEN_DETAILS";
        public const string CPAR_MASTER_DEPARTEMEN_CREATE = "CPAR_MASTER_DEPARTEMEN_CREATE";
        public const string CPAR_MASTER_DEPARTEMEN_EDIT = "CPAR_MASTER_DEPARTEMEN_EDIT";
        public const string CPAR_MASTER_DEPARTEMEN_DELETE = "CPAR_MASTER_DEPARTEMEN_DELETE";
        public const string CPAR_MASTER_PROJECT_INDEX = "CPAR_MASTER_PROJECT_INDEX";
        public const string CPAR_MASTER_PROJECT_DETAILS = "CPAR_MASTER_PROJECT_DETAILS";
        public const string CPAR_MASTER_PROJECT_CREATE = "CPAR_MASTER_PROJECT_CREATE";
        public const string CPAR_MASTER_PROJECT_EDIT = "CPAR_MASTER_PROJECT_EDIT";
        public const string CPAR_MASTER_PROJECT_DELETE = "CPAR_MASTER_PROJECT_DELETE";
        public const string CPAR_MASTER_AUDIT_INDEX = "CPAR_MASTER_AUDIT_INDEX";
        public const string CPAR_MASTER_AUDIT_DETAILS = "CPAR_MASTER_AUDIT_DETAILS";
        public const string CPAR_MASTER_AUDIT_CREATE = "CPAR_MASTER_AUDIT_CREATE";
        public const string CPAR_MASTER_AUDIT_EDIT = "CPAR_MASTER_AUDIT_EDIT";
        public const string CPAR_MASTER_AUDIT_DELETE = "CPAR_MASTER_AUDIT_DELETE";
        public const string CPAR_MASTER_STDREFF_INDEX = "CPAR_MASTER_STDREFF_INDEX";
        public const string CPAR_MASTER_STDREFF_DETAILS = "CPAR_MASTER_STDREFF_DETAILS";
        public const string CPAR_MASTER_STDREFF_CREATE = "CPAR_MASTER_STDREFF_CREATE";
        public const string CPAR_MASTER_STDREFF_EDIT = "CPAR_MASTER_STDREFF_EDIT";
        public const string CPAR_MASTER_STDREFF_DELETE = "CPAR_MASTER_STDREFF_DELETE";
        public const string CPAR_SUMBERCPAR = "CPAR_SUMBERCPAR";
        public const string CPAR_SUMBERCPAR_AUDIT_INDEX = "CPAR_SUMBERCPAR_AUDIT_INDEX";
        public const string CPAR_SUMBERCPAR_AUDIT_DETAILS = "CPAR_SUMBERCPAR_AUDIT_DETAILS";
        public const string CPAR_SUMBERCPAR_AUDIT_CREATE = "CPAR_SUMBERCPAR_AUDIT_CREATE";
        public const string CPAR_SUMBERCPAR_AUDIT_EDIT = "CPAR_SUMBERCPAR_AUDIT_EDIT";
        public const string CPAR_SUMBERCPAR_AUDIT_DELETE = "CPAR_SUMBERCPAR_AUDIT_DELETE";
        public const string CPAR_SUMBERCPAR_COMPLAIN_INDEX = "CPAR_SUMBERCPAR_COMPLAIN_INDEX";
        public const string CPAR_SUMBERCPAR_COMPLAIN_DETAILS = "CPAR_SUMBERCPAR_COMPLAIN_DETAILS";
        public const string CPAR_SUMBERCPAR_COMPLAIN_CREATE = "CPAR_SUMBERCPAR_COMPLAIN_CREATE";
        public const string CPAR_SUMBERCPAR_COMPLAIN_EDIT = "CPAR_SUMBERCPAR_COMPLAIN_EDIT";
        public const string CPAR_SUMBERCPAR_COMPLAIN_DELETE = "CPAR_SUMBERCPAR_COMPLAIN_DELETE";
        public const string CPAR_SUMBERCPAR_REVIEW_INDEX = "CPAR_SUMBERCPAR_REVIEW_INDEX";
        public const string CPAR_SUMBERCPAR_REVIEW_DETAILS = "CPAR_SUMBERCPAR_REVIEW_DETAILS";
        public const string CPAR_SUMBERCPAR_REVIEW_CREATE = "CPAR_SUMBERCPAR_REVIEW_CREATE";
        public const string CPAR_SUMBERCPAR_REVIEW_EDIT = "CPAR_SUMBERCPAR_REVIEW_EDIT";
        public const string CPAR_SUMBERCPAR_REVIEW_DELETE = "CPAR_SUMBERCPAR_REVIEW_DELETE";
        public const string CPAR_SUMBERCPAR_DEFACT_INDEX = "CPAR_SUMBERCPAR_DEFACT_INDEX";
        public const string CPAR_SUMBERCPAR_DEFACT_DETAILS = "CPAR_SUMBERCPAR_DEFACT_DETAILS";
        public const string CPAR_SUMBERCPAR_DEFACT_CREATE = "CPAR_SUMBERCPAR_DEFACT_CREATE";
        public const string CPAR_SUMBERCPAR_DEFACT_EDIT = "CPAR_SUMBERCPAR_DEFACT_EDIT";
        public const string CPAR_SUMBERCPAR_DEFACT_DELETE = "CPAR_SUMBERCPAR_DEFACT_DELETE";
        public const string CPAR_SUMBERCPAR_IMPROVE_INDEX = "CPAR_SUMBERCPAR_IMPROVE_INDEX";
        public const string CPAR_SUMBERCPAR_IMPROVE_DETAILS = "CPAR_SUMBERCPAR_IMPROVE_DETAILS";
        public const string CPAR_SUMBERCPAR_IMPROVE_CREATE = "CPAR_SUMBERCPAR_IMPROVE_CREATE";
        public const string CPAR_SUMBERCPAR_IMPROVE_EDIT = "CPAR_SUMBERCPAR_IMPROVE_EDIT";
        public const string CPAR_SUMBERCPAR_IMPROVE_DELETE = "CPAR_SUMBERCPAR_IMPROVE_DELETE";
        
        public const string CPAR_SUMBERCPAR_OTHER_INDEX = "CPAR_SUMBERCPAR_OTHER_INDEX";
        public const string CPAR_SUMBERCPAR_OTHER_DETAILS = "CPAR_SUMBERCPAR_OTHER_DETAILS";
        public const string CPAR_SUMBERCPAR_OTHER_CREATE = "CPAR_SUMBERCPAR_OTHER_CREATE";
        public const string CPAR_SUMBERCPAR_OTHER_EDIT = "CPAR_SUMBERCPAR_OTHER_EDIT";
        public const string CPAR_SUMBERCPAR_OTHER_DELETE = "CPAR_SUMBERCPAR_OTHER_DELETE";

        public const string CPAR_SUMBERCPAR_CUSTCOMP_INDEX = "CPAR_SUMBERCPAR_CUSTCOMP_INDEX";
        public const string CPAR_SUMBERCPAR_CUSTCOMP_DETAILS = "CPAR_SUMBERCPAR_CUSTCOMP_DETAILS";
        public const string CPAR_SUMBERCPAR_CUSTCOMP_CREATE = "CPAR_SUMBERCPAR_CUSTCOMP_CREATE";
        public const string CPAR_SUMBERCPAR_CUSTCOMP_EDIT = "CPAR_SUMBERCPAR_CUSTCOMP_EDIT";
        public const string CPAR_SUMBERCPAR_CUSTCOMP_DELETE = "CPAR_SUMBERCPAR_CUSTCOMP_DELETE";

        public const string CPAR_LOGBOOK = "CPAR_LOGBOOK";
        public const string CPAR_LOGBOOK_CPAR_INDEX = "CPAR_LOGBOOK_CPAR_INDEX";
        public const string CPAR_LOGBOOK_CPAR_DETAILS = "CPAR_LOGBOOK_CPAR_DETAILS";
        public const string CPAR_LOGBOOK_CPAR_RESPONSE = "CPAR_LOGBOOK_CPAR_RESPONSE";
        public const string CPAR_LOGBOOK_CPAR_VERIFY = "CPAR_LOGBOOK_CPAR_VERIFY";
        public const string CPAR_LOGBOOK_CPAR_CLOSE = "CPAR_LOGBOOK_CPAR_CLOSE";
        public const string CPAR_LOGBOOK_CPAR_CANCEL = "CPAR_LOGBOOK_CPAR_CANCEL";
        public const string CPAR_LOGBOOK_CPAR_CHAT = "CPAR_LOGBOOK_CPAR_CHAT";
        public const string CPAR_LOGBOOK_COMPLAIN_INDEX = "CPAR_LOGBOOK_COMPLAIN_INDEX";
        public const string CPAR_LOGBOOK_COMPLAIN_DETAILS = "CPAR_LOGBOOK_COMPLAIN_DETAILS";
        public const string CPAR_LOGBOOK_COMPLAIN_CPAR = "CPAR_LOGBOOK_COMPLAIN_CPAR";
        public const string CPAR_LOGBOOK_COMPLAIN_CLOSE = "CPAR_LOGBOOK_COMPLAIN_CLOSE";
        public const string CPAR_LOGBOOK_COMPLAIN_CANCEL = "CPAR_LOGBOOK_COMPLAIN_CANCEL";
        public const string CPAR_USER = "CPAR_USER";
        public const string CPAR_USER_INDEX = "CPAR_USER_INDEX";
        public const string CPAR_USER_DETAILS = "CPAR_USER_DETAILS";
        public const string CPAR_USER_CREATE = "CPAR_USER_CREATE";
        public const string CPAR_USER_EDIT = "CPAR_USER_EDIT";
        public const string CPAR_USER_DELETE = "CPAR_USER_DELETE";
        public const string CPAR_USER_ACTIVATE = "CPAR_USER_ACTIVATE";
        public const string CPAR_USER_DEACTIVATE = "CPAR_USER_DEACTIVATE";
    } //End public class valMENU
} //End namespace APPBASE.Svcbiz